Sign Here Please/objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>q-{0}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sign Here Please/objects/Quote_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line Item</label>
    <nameField>
        <label>Quote Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sign Here Please/objects/SignHereSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Organization_Logo_Image__c</fullName>
        <description>Url of the image to use for the logo in the Sign Here Application</description>
        <inlineHelpText>Url of the image to use for the logo in the Sign Here Application</inlineHelpText>
        <label>Organization Logo Image</label>
        <type>Url</type>
    </fields>
    <label>Sign Here Settings</label>
</CustomObject>

Sign Here Please/classes/signHereControllerTest.cls
@isTest
private class signHereControllerTest
{
    static testmethod void runTest1()
    {
        SignHereSettings__c settings = new SignHereSettings__c();
        settings.Organization_Logo_Image__c = 'http://www.google.com/image.gif';
        insert settings;
        
        Account testAccount = new Account();
        testAccount.name = 'test account';
        insert testAccount;
        
        Contact testContact = new Contact();
        testContact.firstname = 'test';
        testContact.lastname = 'guy';
        testContact.accountId = testAccount.id;
        insert testContact;
        
        AccountContactRole thisRole = new AccountContactRole();
        thisRole.accountId = testAccount.id;
        thisRole.contactId = testContact.id;
        thisRole.isPrimary = true;
        thisRole.role = 'Primary';
        insert thisRole;
        
        Quote__c thisQuote = new Quote__c();
        thisQuote.Account__c = testAccount.id;
        insert thisQuote;
        
        Quote_Line_Item__c testLineItem = new Quote_Line_Item__c();
        testLineItem.quote__c = thisQuote.id;
        insert testLineItem;

        PageReference pageRef = Page.signHere;
        pageRef.getParameters().put('pdf','true');
        pageRef.getParameters().put('force_download','true');
        Test.setCurrentPageReference(pageRef);

        ApexPages.StandardController sc = new ApexPages.standardController(thisQuote);
        // create an instance of the controller
        signHereController myPageCon = new signHereController(sc);  
    }

}