Profile Complete Challenge/src/objects/Member__c.object
<CustomObject>
    <description>The members for the application.</description>
    <fields>
        <fullName>Address_Line1__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Paperwork_Received__c</fullName>
        <label>Paperwork Received</label>
        <picklist>
            <picklistValues>
                <fullName>New User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paper Work Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paperwork Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Payment__c</fullName>
        <label>Preferred Payment</label>
        <picklist>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paypal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Profile_Complete__c</fullName>
        <defaultValue>10.00</defaultValue>
        <description>How complete is this profile</description>
        <inlineHelpText>How complete is this profile</inlineHelpText>
        <label>Profile Complete</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Profile_Pic__c</fullName>
        <defaultValue>&quot;http://cloudspokes.s3.amazonaws.com/Cloud_th_100.jpg&quot;</defaultValue>
        <description>The URL to their profile picture.</description>
        <label>Profile Pic</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School /  University</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary_Bio__c</fullName>
        <label>Summary / Bio</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>Eastern Time (US &amp; Canada) -- (GMT-05:00)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Username set as external id sent via integration with SQL.</inlineHelpText>
        <label>Username (ext)</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>ZIP</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sign Here Please/objects/Quote__c.object
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>q-{0}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Profile Complete Challenge/src/classes/memberMethods.cls
public class memberMethods
{
   
    //default variables
    public static double baseProfileComplete = 10.00; 
    public static string defaultPicUrl  = 'whatever.jpg'; 

    //takes a list of member__c records and calculates their profile score.
    public  static void calculateProfileScore(list<member__c> members)
    {
        for(member__c member : members)
        {
            member.Profile_Complete__c = baseProfileComplete;
            
            //If their address information has been filled out
            if(member.Address_Line1__c != null && member.City__c != null && member.Country__c != null && member.State__c != null && member.Zip__c != null && member.Time_Zone__c  != null)
            {
                 member.Profile_Complete__c += 30.00;   
            }          
            //if they have selected a payment method
            if(member.paperwork_Received__c != null && member.Preferred_Payment__c != null)
            {
                member.Profile_Complete__c += 10.00;   
            }
            //if they have selected a non default profile picture
            if(member.Profile_Pic__c != defaultPicUrl)
            {
                member.Profile_Complete__c += 10.00;   
            }                       
            //if have a company
            if(member.Company__c != null)
            {
                member.Profile_Complete__c += 02.50; 
            }
            //if they have a school
            if(member.School__c != null)
            {
                member.Profile_Complete__c += 02.50; 
            }
            //if they have a summary/bio
            if(member.Summary_Bio__c != null)
            {
                member.Profile_Complete__c += 02.50; 
            }
            //if they have a quote
            if(member.Quote__c != null)
            {
                member.Profile_Complete__c += 02.50; 
            }                                    
        }
    }    
    
    @isTest
    public static void memberMethods()
    {
        
        //create an insert a test member
        Member__c thisMember = new Member__c();
        thisMember.email__c = 'test@test.com';
        thisMember.Username__c = 'testman!';
        thisMember.Profile_Pic__c = defaultPicUrl;
        insert thisMember;
        
        //verify they only have the base profile complete percent
        thisMember = [select id, Profile_Complete__c from member__c where id = : thisMember.id];
        system.assertEquals(baseProfileComplete,thisMember.Profile_Complete__c);
        
        //fill out their profile
        thisMember.Address_Line1__c = '5555 TEST Street';
        thisMember.City__c = 'Nowhere Town';
        thisMember.Country__c = 'US';
        thisMember.State__c = 'MN';
        thisMember.Zip__c = '52342';
        thisMember.Time_Zone__c  = 'Eastern Time (US & Canada) -- (GMT-05:00)';
        thisMember.Paperwork_Received__c = 'true';
        thisMember.Preferred_Payment__c = 'Paypal';
        thisMember.Profile_Pic__c = 'test.jpg';
        thisMember.Company__c = 'test';
        thisMember.School__c ='harvard';
        thisMember.Summary_Bio__c = 'Im not real';
        thisMember.Quote__c = 'This is a quote';
        
        update thisMember;
        
        //make sure their profile complete percent is that maximum it can be (which is 70% as of this writting)
        thisMember = [select id, Profile_Complete__c from member__c where id = : thisMember.id];
        system.assertEquals(70.00,thisMember.Profile_Complete__c);        
        
    }
}